services:
  - type: web
    name: background-remover
    env: python
    plan: free
    buildCommand: curl -sSL https://install.python-poetry.org | python3 - && poetry install
    startCommand: poetry run gunicorn app:app
    pythonVersion: 3.10.12
    scaling:
      minInstances: 1
      maxInstances: 1
