services:
  - type: web
    name: background-remover
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    scaling:
      minInstances: 1
      maxInstances: 1
